# Navigation Links
main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: Publications
    url: /publication/
    weight: 30
  - name: Opportunities
    url: /opportunities/
    weight: 40
